# https://doc.traefik.io/traefik/user-guides/docker-compose/basic-example/#docker-compose-basic-example

version: "3.9"

services:
  ###################################
  # Traefik
  ###################################
  traefik-prod:
    image: traefik:v2.8.4
    container_name: traefik_service
    restart: always
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
      - 8080:8080
      #- 8081:8081
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - ./logs/traefik:/etc/traefik/log
      # Static Configuration
      - ./config/static-conf.yml:/etc/traefik/traefik.yml:ro
      # Dynamic Configuration
      - ./config/dynamic-conf.yml:/etc/traefik/dynamic-conf.yml:ro 
      # Ssl
      - ./certs:/etc/certs
    environment:
      - TZ=America/Fortaleza
    networks:
      - traefik
      
networks:
 traefik:
   name: traefik
   driver: bridge