# by: Erivando Sena | DevOps/SRE | UNILAB
# docker compose -p pgd-docker-sqlserver -f docker-compose.mssqlserver.yml up -d 
# docker compose -p pgd-docker-sqlserver -f docker-compose.mssqlserver.yml up -d (Compose V2.x)

version: "3.9"

services:
  # api
  api-sqlserver:
    image: erivando/pdg-susep-ubuntu20-mssqlserver:latest
    container_name: api_service_sqlserver
    restart: always
    working_dir: /opt/pgd/api/
    command: dotnet Susep.SISRH.WebApi.dll
    volumes:
      - ./config/api/Settings/mssqlserver:/opt/pgd/api/Settings:ro
      - ./logs/api/log_pgd_mssqlserver:/opt/pgd/api/Logs:rw
    environment:
      - ASPNETCORE_URLS=http://+:80
      - TZ=America/Fortaleza
      - ASPNETCORE_ENVIRONMENT=Homolog
      # Email
      - emailOptions__EmailRemetente=teletrabalho@noreply.domainorgao.edu.br
      - emailOptions__NomeRemetente=Programa de Gestão - Susep
      - emailOptions__SmtpServer=smtp.noreply.domainorgao.edu.br
      - emailOptions__Port=25
      # Ldap
      - ldapOptions__Configurations__0__Url=xxxxxx
      - ldapOptions__Configurations__0__Port=xxxxxx
      - ldapOptions__Configurations__0__BindDN=xxxxxx
      - ldapOptions__Configurations__0__BindPassword=xxxxxx
      - ldapOptions__Configurations__0__SearchBaseDC=xxxxxx
      - ldapOptions__Configurations__0__SearchFilter=xxxxxx
      - ldapOptions__Configurations__0__CpfAttributeFilter=xxxxxx
      - ldapOptions__Configurations__0__EmailAttributeFilter=xxxxxx
      # Database
      - ConnectionStrings__DefaultConnection=Server=mssqlserver,1433;Database=pgd_staging;User Id=admin;Password=Sql@server2019Express;
    networks:
      - pgd

  # gateway
  gateway-sqlserver:
    image: erivando/pdg-susep-ubuntu20-mssqlserver:latest
    container_name: gateway_service_sqlserver
    restart: always
    working_dir: /opt/pgd/gateway/
    command: dotnet Susep.SISRH.ApiGateway.dll
    volumes:
      - ./config/gateway/Settings/mssqlserver:/opt/pgd/gateway/Settings:ro
      - ./logs/gateway/log_pgd_mssqlserver:/opt/pgd/gateway/Logs:rw
    environment:
      - ASPNETCORE_URLS=http://+:80
      - TZ=America/Fortaleza
      - ASPNETCORE_ENVIRONMENT=Homolog
    networks:
      - pgd
    depends_on:
      - api-sqlserver

  # app
  app-sqlserver:
    image: erivando/pdg-susep-ubuntu20-mssqlserver:latest
    container_name: app_service_sqlserver
    restart: always
    working_dir: /opt/pgd/app/    
    command: dotnet Susep.SISRH.WebApp.dll
    volumes:
      - ./config/app/mssqlserver/env.js:/opt/pgd/app/ClientApp/dist/env.js:ro
    environment:
      #- ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - TZ=America/Fortaleza
    networks:
      - pgd
    depends_on:
      - api-sqlserver
      - gateway-sqlserver

networks:
  pgd:
    external: true
    name: traefik